export enum Reaction {
    LIKE,
    DISLIKE,
    LOVE,
    EMPHASIZE,
    QUESTION,
    HAHAHAHA
}

export enum University {
    ISLAMIC_UNIVERSITY_OF_GAZA,
    ALQUDS_OPEN_UNIVERSITY,
    ARAB_AMERICAN_UNIVERSITY,
    BETHLEHEM_UNIVERSITY,
    ANNAJAH_NATIONAL_UNIVERSITY,
    UNIVERSITY_OF_PALESTINE,
    ALQUDS_UNIVERSITY,
    ALAQSA_UNIVERSITY,
    PALESTINE_POLYTECHNIC_UNIVERSITY,
    BIRZEIT_UNIVERSITY,
    HEBRON_UNIVERSITY,
    ALAZHAR_UNIVERSITY,
    ALISTIQLAL_UNIVERSITY,
    PALESTINE_TECHNICAL_UNIVERSITY_KADOORIE,
    PALESTINE_TECHNICAL_COLLEGE,
    PALESTINE_AHLIYA_UNIVERSITY,
    DAR_ALKALIMA_UNIVERSITY,
}

export enum GroupRole {
    MEMBER, ADMIN
}

export enum MessageReceiver {
    USER, GROUP_CHAT
}

export enum NotificationType {
    FOLLOW_REQUEST,
    POST_SHARE,
    POST_LIKE,
    STORY_LIKE,
    STORY_REPLY,
    COMMENT_REPLY,
    COMMENT,
    COMMENT_LIKE,
    MESSAGE,
    GROUP_MESSAGE,
}

export enum View {
    PUBLIC, COMMUNITY, PRIVATE
}

export enum Gender {
    MALE, FEMALE
}

export enum Status {
    ONLINE, OFFLINE
}
